---
- name: Disable swap
  shell: swapoff -a

- name: Add k8s configiguration file to /etc/modules-load.d/
  copy:
    src: modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root

- name: Ensure br_netfilter module is loaded
  shell: modprobe br_netfilter

- name: Ensure iptables corretly see bridged traffic
  copy:
    src: iptables.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root

- name: Force sysctl to load settings from all system conf files
  shell: sysctl --system

- name: Download the Google Cloud public signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add the K8s apt repository
  apt_repository:
    repo: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] 
      https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
    state: present

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - kubelet={{ kubernetes_version }}
    - kubeadm={{ kubernetes_version }}
    - kubectl={{ kubernetes_version }}
