---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: physical-broker-latency
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'physical-broker'
  delay:
    latency: '50ms'
    correlation: '25'
    jitter: '50ms'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: physical-broker-loss
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'physical-broker'
  loss:
    loss: '10'
    correlation: '25'
