---
apiVersion: v1
kind: ConfigMap
metadata:
  name: digital-twin-1
data:
  dt_conf.yaml: |
    digitalTwinId: digital-twin-1
    targetDeviceId: iiot-device-1
    physicalMqttBrokerAddress: physical-broker.default.svc.cluster.local
    physicalMqttBrokerPort: 1883
    digitalMqttBrokerAddress: digital-broker.default.svc.cluster.local
    digitalMqttBrokerPort: 1883
    metricsEnabled: true
    httpApiPort: 5555
    prometheusHttpApiPort: 1234
    expectedMsgSec: 1
    observationBucketType: default
    observationBucketStart: 0.0
    observationBucketWidth: 0.005
    observationBucketCount: 1001
    primeNumbersComputationCount: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin-1
  labels:
    app: digital-twin-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-twin-1
  template:
    metadata:
      labels:
        app: digital-twin-1
      annotations:
        prometheus.io/port: "1234"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: digital-twin
        image: <your-container-registry>
        imagePullPolicy: Always
        ports:
        - name: http-api
          protocol: TCP
          containerPort: 5555
        - name: http-metrics
          protocol: TCP
          containerPort: 1234
        volumeMounts:
        - name: digital-twin-config
          mountPath: /usr/local/src/mvnapp/dt_conf.yaml
          subPath: dt_conf.yaml
          readOnly: true
      volumes:
      - name: digital-twin-config
        configMap: 
          name: digital-twin-1
---
apiVersion: v1
kind: Service
metadata:
  name: digital-twin-1
spec:
  type: NodePort
  selector:
    app: digital-twin-1
  ports:
  - name: http-metrics
    protocol: TCP
    port: 80
    targetPort: 1234
  - name: http-api
    protocol: TCP
    port: 5555
    targetPort: 5555
