---
apiVersion: v1
kind: ConfigMap
metadata:
  name: physical-broker
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
    persistence true
    persistence_location /mosquitto/data/
    log_type all
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: physical-broker
  labels:
    app: physical-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: physical-broker
  template:
    metadata:
      labels:
        app: physical-broker
    spec:
      containers:
      - name: physical-broker
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: data
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      initContainers:
      - name: copy
        image: eclipse-mosquitto
        command: ["sh", "-c", "cp /tmp/config/mosquitto.conf /tmp/data/"]
        volumeMounts:
        - mountPath: /tmp/config
          name: config
        - mountPath: /tmp/data
          name: data
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap: 
          name: physical-broker
---
apiVersion: v1
kind: Service
metadata:
  name: physical-broker
spec:
  selector:
    app: physical-broker
  ports:
  - name: tcp-default
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: tcp-websocket
    protocol: TCP
    port: 9001
    targetPort: 9001
