---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-manager-gdjpo

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-manager-gdjpo
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-manager-gdjpo
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-manager-gdjpo
  namespace: default
roleRef:
  kind: Role
  name: role-default-manager-gdjpo
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: token-default-manager-gdjpo
  namespace: default
  annotations:
    kubernetes.io/service-account.name: account-default-manager-gdjpo
type: kubernetes.io/service-account-token
