---
- name: Download helm installer
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: $HOME/get-helm-3.sh
    mode: '0700'

- name: Install helm
  command: $HOME/get-helm-3.sh

- name: Add chaos-mesh repository
  kubernetes.core.helm_repository:
    name: chaos-mesh
    repo_url: "https://charts.chaos-mesh.org"

- name: Create chaos-testing namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: chaos-testing
    state: present

- name: Install chaos-mesh
  kubernetes.core.helm:
    name: chaos-mesh
    chart_ref: chaos-mesh/chaos-mesh
    release_namespace: chaos-testing
    values:
      chaosDaemon:
        runtime: crio
        socketPath: /var/run/crio/crio.sock
      controllerManager:
        enableFilterNamespace: true
      version: "{{ chaos_mesh_version }}"

- name: Enable chaos-mesh in default namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: default
    definition:
      metadata:
        annotations:
          chaos-mesh.org/inject: enabled
    state: patched
  
- name: Render template to access chaos dashboard remotely
  template:
    src: chaos-dashboard.j2
    dest: $HOME/chaos-dashboard.yaml

- name: Deploy gateway and virtual service to access chaos dashboard remotely
  kubernetes.core.k8s:
    src: $HOME/chaos-dashboard.yaml
    state: present

- name: Copy rbac for manager profile in default namespace
  copy:
    src: chaos-rbac.yaml
    dest: $HOME/chaos-rbac.yaml

- name: Create manager profile in default namespace
  kubernetes.core.k8s:
    src: $HOME/chaos-rbac.yaml
    state: present
