---
- hosts: masters
  become: no
  tags:
  - chaos
  roles:
  - rollback/chaos-mesh

- hosts: masters
  become: no
  tags:
  - telemetry
  roles:
  - rollback/istio/addons

- hosts: masters
  become: no
  tags:
  - mesh
  roles:
  - rollback/istio

- hosts: workers
  become: yes
  tags:
  - join
  roles:
  - rollback/k8s/join

- hosts: masters
  become: yes
  tags:
  - init
  roles:
  - rollback/flannel
  - rollback/k8s/init

- hosts: all
  become: yes
  tags:
  - setup
  roles:
  - rollback/k8s/common
  - rollback/crio
  - rollback/common
