---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: physical-broker-0-0-delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'physical-broker'
  delay:
    latency: '2.5ms'
    correlation: '25'
    jitter: '2.5ms'
