---
- name: Install packages needed to use community.kubernetes collection
  block:
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Install openshift Python package
    pip:
      name: openshift
      state: present

- name: Populate service facts
  service_facts:

- name: Ensure kubelet is not running
  service_facts:
  until:
  - ansible_facts['services']['kubelet.service']['state'] != 'running'
  retries: 2
  delay: 5
  failed_when: false

- name: Initialize the K8s cluster
  shell: >
    kubeadm init 
    --apiserver-advertise-address={{ apiserver_advertise_address }} 
    --pod-network-cidr={{ pod_network_cidr }}
  when:
  - ansible_facts['services']['kubelet.service']['state'] != 'running'

- name: Create ~/.kube diectory
  become: no
  file:
    path: $HOME/.kube
    state: directory

- name: Copy K8s config file in ~/.kube
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Set --node-ip for kubelet
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"'
    line: 'Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --node-ip={{ kubelet_node_ip }}"'

- name: Restart service kubelet
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted
