---
- name: Delete gateways and virtual services to access addons remotely
  kubernetes.core.k8s:
    src: $HOME/{{ item }}.yaml
    state: absent
  loop:
  - grafana
  - jaeger
  - kiali
  - prometheus

- name: Delete config files to access addons remotely
  file:
    path: $HOME/{{ item }}.yaml
    state: absent
  loop:
  - grafana
  - jaeger
  - kiali
  - prometheus

- name: Delete telemetry addons to the cluster
  kubernetes.core.k8s:
    src: $HOME/istio-{{ istio_version }}/samples/addons/{{ item }}.yaml
    state: absent
  loop:
  - grafana
  - jaeger
  - kiali
  - prometheus
