---
- name: Uninstall kubelet, kubeadm, and kubectl
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Remove the K8s apt repository
  apt_repository:
    repo: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] 
      https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
    state: absent

- name: Delete the Google Cloud public signing key
  file:
    path: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: absent

- name: Unload br_netfilter module
  shell: modprobe -r br_netfilter

- name: Delete /etc/modules-load.d/k8s.conf
  file:
    path: /etc/modules-load.d/k8s.conf
    state: absent

- name: Delete /etc/sysctl.d/k8s.conf
  file:
    path: /etc/sysctl.d/k8s.conf
    state: absent

- name: Force sysctl to load settings from all system conf files
  shell: sysctl --system

- name: Enable swap
  shell: swapon -a
